# Site settings
title: I am Jiale!
email: jiale.lou@utas.edu.au
url: https://example.github.io
description: "Jiale started his PhD at Institute for Marine & Antarctic Studies (IMAS), University of Tasmania (UTAS) in February 2017. His research focuses on the predictability of the interdecadal Pacific oscillation. He seeks to identify the mechanisms that initiate transitions between IPO phases and quantify the predictive skill of the IPO.
Prior to starting his PhD at the UTAS, Jiale completed a Master of Science degree (2016) in Global Environment Change at the Beijing Normal University (China). During his masters period, he did some research work about the decadal predictability and variability for the atmospheric circulations in the Northern Hemisphere."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000006'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: ORCID
    url: https://orcid.org/my-orcid
  - title: facebook
    url: www.facebook.com/jiale.lou
  - title: Jiale
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
